prometheus.exporter.unix "dell_metrics" {
  set_collectors = ["textfile"]
  textfile {
    directory = "/opt/dell-exporter"
  }
}

prometheus.scrape "dell_exporter" {
  scrape_interval = "60s"
  targets    = prometheus.exporter.unix.dell_metrics.targets
  job_name   = "dell_exporter"
  forward_to = [prometheus.remote_write.grafana.receiver]
}

prometheus.remote_write "grafana" {
  endpoint {
    url = "https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push"
    basic_auth {
      username = "2361797"
      password = "GRAFANA_API_KEY_PLACEHOLDER"
    }
  }
}

// IPMI exporter scrape (local ipmi_exporter on 9290)
prometheus.scrape "ipmi_exporter" {
  scrape_interval = "60s"
  targets = [
    {
      address = "127.0.0.1:9290"
      params = {
        target = ["localhost"]
        module = ["default"]
      }
    },
  ]
  job_name   = "ipmi_exporter"
  forward_to = [prometheus.remote_write.grafana.receiver]
}
